version: 2.1
jobs:
  build:
    executor: python/default
    parallelism: 10
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - python/install-packages:
          pkg-manager: poetry
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          command: |
            circleci tests glob "./*/tests/*.py" | circleci tests split > /tmp/tests-to-run --split-by=timings --timings-type=classname
            poetry run pytest --cov-report term-missing --cov=tap_ask_nicely /tmp/tests-to-run
            poetry run coveralls
          name: Run Tests and Upload Coverage
      - store_test_results:
          path: test_results/pytest/
orbs:
  python: circleci/python@1.4.0
workflows:
  main:
    jobs:
      - build
